services:
  - type: web
    name: artmintflow-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: NFT_STORAGE_API
        value: 5d9162ed10545d77536369469f9b32b5